on:
  push:
    branches:
      - main
  # pull_request:
    # types:
    #   - opened # default
    #   - reopened # default
    #   - synchronize # default
    #   - ready_for_review
jobs:
  echo:
    # if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World"
      - name: Greeting
        run: echo "Goodbye World"
