on:
  push:
    branches:
      - main
jobs:
  echo-push:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World push"
      - name: Greeting
        run: echo "Goodbye World push"
