name: sql datetime check
on:
  # push:
  # branches:
  #   - main
  # paths:
  #   - "migrations/**"
  pull_request:
    # paths:
    #   - "migrations/**"

jobs:
  # 1. mainブランチから最新のmigrationファイルの名前を取得
  check_latest:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.latest_sql_file.outputs.latest_sql_file }}
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }} # PR先のブランチをチェックアウト
      - name: Get latest SQL file
        id: latest_sql_file
        run: |
          echo "latest_sql_file=$(ls migrations | tail -n 1)" >> $GITHUB_OUTPUT
      # - name: Echo latest SQL file
      #   run: |
      #     echo "${{steps.latest_sql_file.outputs.latest_sql_file}}"

  # 2. 作成したmigrationファイル名が1で取得した最新のmigrationファイル名よりも後になっているか確認
  check_diff:
    runs-on: ubuntu-latest
    needs: check_latest
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}
      - name: Find oldest added sql file
        id: find_oldest_added_sql_file
        run: |
          echo "added_sql_files=$(git diff origin/${{ github.base_ref }} ${{ github.head_ref }} --name-only -- '***.sql')" >> $GITHUB_OUTPUT
      - name: Compare sql files
        run: |
          echo "oldest added sql file"
          echo "${{steps.find_oldest_added_sql_file.outputs.added_sql_files}}"

