name: Test

on:
    pull_request:
    workflow_dispatch:
    # in dev pranches
      inputs:
        environment:
          required: true
          options:
            - 'dev'
            - 'stg'
            - 'prod'

jobs:
  Echo:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Echo Hello
        run: echo "Hello"